-- ===== Secure Database Demo Script =====
-- Run as a privileged MySQL user (root) on a test instance.
-- REPLACE placeholders BEFORE using in production.

-- 1) Safety: drop old demo DB (optional)
DROP DATABASE IF EXISTS secure_db;
CREATE DATABASE secure_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE secure_db;

-- ===== Tables =====
-- Users: password_hash should be generated by your application using bcrypt (recommended).
CREATE TABLE users (
  user_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(128) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','user') NOT NULL DEFAULT 'user',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Clients: store SSN (or other PII) encrypted using AES_ENCRYPT
CREATE TABLE clients (
  client_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(50),
  ssn VARBINARY(512),                 -- AES_ENCRYPT output stored as VARBINARY
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Audit log for actions (insert/update/delete) and manual events
CREATE TABLE audit_logs (
  log_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  action VARCHAR(100) NOT NULL,
  object_type VARCHAR(50),
  object_id VARCHAR(100),
  details TEXT,
  performed_by VARCHAR(128),
  performed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ===== Application-level SECRET (DEMO ONLY) =====
-- IMPORTANT: Replace this with secure retrieval from environment or secret manager.
-- This variable will be used by the stored procedures below.
SET @APP_ENCRYPTION_KEY = 'REPLACE_WITH_STRONG_KEY';  -- <<< CHANGE THIS before any real use

-- ===== Stored Procedures (use parameters to avoid SQL injection) =====
-- Add client (application should call this with sanitized inputs)
DELIMITER $$
CREATE PROCEDURE sp_add_client(
  IN p_name VARCHAR(200),
  IN p_email VARCHAR(255),
  IN p_phone VARCHAR(50),
  IN p_ssn_plain VARCHAR(255),
  IN p_actor_username VARCHAR(128)     -- who performed the action
)
SQL SECURITY INVOKER
BEGIN
  -- insert encrypted SSN using the application key (do NOT store key in DB in production)
  INSERT INTO clients (name, email, phone, ssn)
  VALUES (p_name, p_email, p_phone, AES_ENCRYPT(p_ssn_plain, @APP_ENCRYPTION_KEY));

  -- log action (audit)
  INSERT INTO audit_logs(action, object_type, object_id, details, performed_by)
  VALUES ('INSERT_CLIENT', 'clients', LAST_INSERT_ID(), CONCAT('inserted client ', p_name), p_actor_username);
END$$
DELIMITER ;

-- Get decrypted SSN (admin-only): procedure checks the user's role in users table.
DELIMITER $$
CREATE PROCEDURE sp_get_client_ssn(
  IN p_client_id INT,
  IN p_requestor_username VARCHAR(128)
)
SQL SECURITY INVOKER
BEGIN
  DECLARE v_role ENUM('admin','user') DEFAULT 'user';

  -- find requestor role
  SELECT role INTO v_role FROM users WHERE username = p_requestor_username LIMIT 1;

  IF v_role IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Requestor not found';
  END IF;

  IF v_role != 'admin' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Unauthorized: admin role required';
  END IF;

  -- Return decrypted ssn and client info (only for admins)
  SELECT client_id, name, email, phone, CAST(AES_DECRYPT(ssn, @APP_ENCRYPTION_KEY) AS CHAR(255)) AS ssn_plain
  FROM clients
  WHERE client_id = p_client_id;
END$$
DELIMITER ;

-- Update client (example uses AES_ENCRYPT when ssn is provided)
DELIMITER $$
CREATE PROCEDURE sp_update_client(
  IN p_client_id INT,
  IN p_name VARCHAR(200),
  IN p_email VARCHAR(255),
  IN p_phone VARCHAR(50),
  IN p_ssn_plain VARCHAR(255),          -- pass NULL if not updating SSN
  IN p_actor_username VARCHAR(128)
)
SQL SECURITY INVOKER
BEGIN
  -- Perform update; only update ssn if provided (not null)
  IF p_ssn_plain IS NULL THEN
    UPDATE clients
    SET name = p_name, email = p_email, phone = p_phone
    WHERE client_id = p_client_id;
  ELSE
    UPDATE clients
    SET name = p_name, email = p_email, phone = p_phone,
        ssn  = AES_ENCRYPT(p_ssn_plain, @APP_ENCRYPTION_KEY)
    WHERE client_id = p_client_id;
  END IF;

  INSERT INTO audit_logs(action, object_type, object_id, details, performed_by)
  VALUES ('UPDATE_CLIENT', 'clients', p_client_id, CONCAT('updated client ', p_client_id), p_actor_username);
END$$
DELIMITER ;

-- Delete client
DELIMITER $$
CREATE PROCEDURE sp_delete_client(
  IN p_client_id INT,
  IN p_actor_username VARCHAR(128)
)
SQL SECURITY INVOKER
BEGIN
  DELETE FROM clients WHERE client_id = p_client_id;

  INSERT INTO audit_logs(action, object_type, object_id, details, performed_by)
  VALUES ('DELETE_CLIENT', 'clients', p_client_id, CONCAT('deleted client ', p_client_id), p_actor_username);
END$$
DELIMITER ;

-- ===== Views (masking for non-admins) =====
-- Public view: masked SSN for normal consumption
CREATE VIEW v_clients_public AS
SELECT client_id, name, email, phone,
       CONCAT('***REDACTED***') AS ssn_mask,
       created_at
FROM clients;

-- ===== Triggers (audit on direct DML; stored procs also create audit rows) =====
DELIMITER $$
CREATE TRIGGER trg_clients_insert
AFTER INSERT ON clients
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs(action, object_type, object_id, details, performed_by)
  VALUES ('INSERT_CLIENT_TRIGGER', 'clients', NEW.client_id, CONCAT('inserted via direct SQL: ', NEW.name), SUBSTRING_INDEX(USER(),'@',1));
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER trg_clients_update
AFTER UPDATE ON clients
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs(action, object_type, object_id, details, performed_by)
  VALUES ('UPDATE_CLIENT_TRIGGER', 'clients', NEW.client_id, CONCAT('updated via direct SQL'), SUBSTRING_INDEX(USER(),'@',1));
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER trg_clients_delete
AFTER DELETE ON clients
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs(action, object_type, object_id, details, performed_by)
  VALUES ('DELETE_CLIENT_TRIGGER', 'clients', OLD.client_id, CONCAT('deleted via direct SQL'), SUBSTRING_INDEX(USER(),'@',1));
END$$
DELIMITER ;

-- ===== Least-privilege MySQL user accounts (DEMO) =====
-- NOTE: choose strong passwords and limit host as appropriate (e.g., 'app_user'@'app-host.example.com')
-- Replace 'CHANGE_APP_USER_PW' and 'CHANGE_ADMIN_PW' with strong secrets.

-- Remove old demo users if exist (optional)
DROP USER IF EXISTS 'app_user'@'localhost';
DROP USER IF EXISTS 'app_admin'@'localhost';

-- Create restricted app user: can call procedures and do limited SELECT/INSERT
CREATE USER 'app_user'@'localhost' IDENTIFIED BY 'CHANGE_APP_USER_PW';
GRANT EXECUTE ON secure_db.* TO 'app_user'@'localhost';
GRANT SELECT ON secure_db.v_clients_public TO 'app_user'@'localhost';
GRANT INSERT ON secure_db.clients TO 'app_user'@'localhost';
GRANT INSERT ON secure_db.audit_logs TO 'app_user'@'localhost';

-- Create app admin user: broader privileges (but still limited to DB)
CREATE USER 'app_admin'@'localhost' IDENTIFIED BY 'CHANGE_ADMIN_PW';
GRANT EXECUTE ON secure_db.* TO 'app_admin'@'localhost';
GRANT ALL PRIVILEGES ON secure_db.clients TO 'app_admin'@'localhost';
GRANT ALL PRIVILEGES ON secure_db.audit_logs TO 'app_admin'@'localhost';
GRANT ALL PRIVILEGES ON secure_db.users TO 'app_admin'@'localhost';
GRANT SELECT ON secure_db.* TO 'app_admin'@'localhost';

-- Flush privileges
FLUSH PRIVILEGES;

-- ===== Example: insert demo admin user (bcrypt recommended via app; this is placeholder) =====
-- NOTE: Replace the password hash below with a bcrypt hash generated by your environment/tool.
INSERT INTO users (username, password_hash, role)
VALUES ('admin', '$2y$12$EXAMPLE_BCRYPT_HASH_REPLACE_ME', 'admin');

-- ===== Helpful Constraints & Indexes =====
ALTER TABLE clients ADD INDEX idx_email (email);

-- ===== Demo: Example usage comments =====
-- To add a client (application should call as prepared call):
-- CALL sp_add_client('Alice Smith','alice@example.com','555-1234','123-45-6789','admin');

-- To get a client's decrypted SSN (admin only):
-- CALL sp_get_client_ssn(1,'admin');

-- To update a client:
-- CALL sp_update_client(1,'Alice Smith','alice@new.com','555-5555',NULL,'admin');

-- ===== End of script =====
